version: "3"

services:
  rest_api:
    build: .
    restart: always
    environment:
      - DATABASE_URL=mysql+pymysql://user:password@db/items_db
      - ADMIN_PASSWORD=password
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=items_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"