POST http://127.0.0.1:8000/uploadfile/ HTTP/1.1
Host: 127.0.0.1:8000
Content-Type: multipart/form-data; boundary=----CustomBoundary123

------CustomBoundary123
Content-Disposition: form-data; name="file"; filename="50.jpg"
Content-Type: image/jpeg

< ../to_be_uploaded/50.jpg
------CustomBoundary123--