POST http://127.0.0.1:8000/uploadfile/ HTTP/1.1
Host: 127.0.0.1:8000
Content-Type: multipart/form-data; boundary=----CustomBoundary123

------CustomBoundary123
Content-Disposition: form-data; name="file"; filename="moby_dick.txt"
Content-Type: text/plain

< ../to_be_uploaded/moby_dick.txt
------CustomBoundary123--